# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_actualizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='is_nuevo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='is_ofert',
        ),
    ]
