# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20161107_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendidos',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
