# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('seccion', models.CharField(blank=True, help_text=b'El id donde se colocara', max_length=100)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('template', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[(b'imagenes', b'Imagenes'), (b'productos', b'Productos')], max_length=100)),
                ('num_mostrar', models.PositiveIntegerField(default=1)),
                ('navegacion', models.BooleanField(default=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carruseles', to='cmsweb.Pagina')),
            ],
        ),
        migrations.AddField(
            model_name='bloque',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
