# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsweb', '0002_auto_20161106_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecarrusel',
            name='carrusel',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_carrusel', to='cmsweb.Carrusel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagecarrusel',
            name='bloque',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_bloque', to='cmsweb.Bloque'),
        ),
    ]
