# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsweb', '0003_auto_20161106_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecarrusel',
            name='bloque',
        ),
    ]
