# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsweb', '0004_remove_imagecarrusel_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel',
            name='items',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
