# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0002_auto_20151127_1406'),
        ('pedido', '0010_metodoenvio_restriccion_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodoenvio',
            name='exepciones',
            field=models.ManyToManyField(blank=True, help_text=b'Menos en este esta habilitado', related_name='restricciones_menos', to='ubigeo.Ubigeo'),
        ),
        migrations.AlterField(
            model_name='metodoenvio',
            name='restricciones',
            field=models.ManyToManyField(blank=True, help_text=b'Solo en este lugar esta habilitado', related_name='restricciones_solo', to='ubigeo.Ubigeo'),
        ),
    ]
